version: '3.9'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - mynetwork

  data_seeder:
    build: ./data_seeder
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    depends_on:
      - postgresql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
