name: Changelog Workflow

on:
  pull_request:
    branches: [ dev ]
    types: [ closed ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set file permissions
        run: |
          chmod 777 ./changelog.md

      - name: Update changelog
        uses: danpetitt/changelog-file-generator@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_version: 'v1.0.0'
          file: './changelog.md'
          files_to_commit: 'changelog.md'
          branch: dev
          user: 'elhadedynader@gmail.com'
          userName: 'naderelhadedy'
