name: Changelog Workflow

on:
  pull_request:
    branches: [ dev ]
    types: [ closed ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          committer_username: 'naderelhadedy'
          committer_email: 'elhadedynader@gmail.com'

