name: Changelog Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          committer_username: 'naderelhadedy'
          committer_email: 'elhadedynader@gmail.com'
          release_version: ${{ github.event.inputs.release_version }}

