name: Changelog Workflow

on:
  pull_request:
    branches: [ dev ]
    types: [ closed ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conventional-changelog
        run: pip install conventional-changelog

      - name: Generate changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "elhadedynader@gmail.com"
          git config --local user.name "naderelhadedy"
          git add CHANGELOG.md
          git commit -m "docs: updated changelog"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
