name: Linting Workflow

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint
        run: |
          pylint --output-format=colorized ./app
